H = 0.1           # m
B = 0.1           # m
N_H = 4           # nodes per H
N_B = 4           # nodes per B
C = 700           # J/kg*C  - specific heat
K = 25            # W/m*C   - conductivity
RO = 7800         # kg/m3   - density
ALFA = 300        # W/m2K   
T_AMBIENT = 1200  
T_START = 100
TM_STEP = 50     
N_STEPS = 10
SCHEMA_N = 1     